name: Linting And Type Checking


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip install mypy certifi

    - name: Run mypy
      run: mypy .

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: astral-sh/ruff-action@v3
    - run: ruff check --fix
    - run: ruff format
