name: Felt Python Linting And Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Lint and format using Ruff
      uses: astral-sh/ruff-action@v3
      run: ruff check --fix
      run: ruff format --diff
